//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Brand
{
    public int b_id { get; set; }
    public string b_name { get; set; }
}

public partial class Category
{
    public int c_id { get; set; }
    public string c_name { get; set; }
}

public partial class Product
{
    public int p_id { get; set; }
    public string p_name { get; set; }
    public Nullable<int> b_id { get; set; }
    public Nullable<int> c_id { get; set; }
    public Nullable<decimal> p_price { get; set; }
    public string p_color { get; set; }
    public string p_image_link { get; set; }
    public Nullable<System.DateTime> p_posted_date { get; set; }
    public Nullable<int> s_id { get; set; }
}

public partial class Supplier
{
    public int s_id { get; set; }
    public string s_name { get; set; }
    public string s_email { get; set; }
    public string s_phone { get; set; }
    public string s_loc { get; set; }
    public string s_password { get; set; }
}
